name = "Ferrule"
grammar = "ferrule"
path_suffixes = ["fe"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 2
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]

word_characters = ["_"]

# Tell Zed which LSP to use for this language
language_servers = ["ferrule-lsp"]

